# Generated by Django 5.0.6 on 2025-05-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_nm', models.CharField(max_length=100)),
                ('dep', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
